"""Build assets/js/kenya-map.js from geoBoundaries Kenya ADM1 (counties).

Source: https://www.geoboundaries.org (gbOpen KEN ADM1, RCMRD GeoPortal, public domain).
Usage: python tools/build_kenya_map.py path/to/geoBoundaries-KEN-ADM1_simplified.geojson
"""
import json
import math
import sys

W = 400            # SVG width in map units
PAD = 6            # padding around the country
TOL = 0.45         # simplification tolerance in map units
RENAME = {"Taita Taveta": "Taita-Taveta", "Tharaka": "Tharaka-Nithi"}


def rdp(points, tol):
    """Ramer-Douglas-Peucker line simplification."""
    if len(points) < 3:
        return points
    (x1, y1), (x2, y2) = points[0], points[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = math.hypot(dx, dy) or 1e-12
    best_i, best_d = 0, -1.0
    for i in range(1, len(points) - 1):
        x, y = points[i]
        d = abs(dy * x - dx * y + x2 * y1 - y2 * x1) / norm
        if d > best_d:
            best_i, best_d = i, d
    if best_d > tol:
        left = rdp(points[: best_i + 1], tol)
        return left[:-1] + rdp(points[best_i:], tol)
    return [points[0], points[-1]]


def rdp_ring(ring, tol):
    """Simplify a closed ring: split at the point farthest from the start, simplify each half."""
    x0, y0 = ring[0]
    k = max(range(len(ring)), key=lambda i: math.hypot(ring[i][0] - x0, ring[i][1] - y0))
    if k == 0:
        return ring
    return rdp(ring[: k + 1], tol)[:-1] + rdp(ring[k:], tol)


def ring_area_centroid(ring):
    a = cx = cy = 0.0
    for (x1, y1), (x2, y2) in zip(ring, ring[1:] + ring[:1]):
        cross = x1 * y2 - x2 * y1
        a += cross
        cx += (x1 + x2) * cross
        cy += (y1 + y2) * cross
    a /= 2
    if abs(a) < 1e-9:
        xs, ys = zip(*ring)
        return 0.0, sum(xs) / len(xs), sum(ys) / len(ys)
    return a, cx / (6 * a), cy / (6 * a)


def main(path):
    data = json.load(open(path, encoding="utf-8"))
    polys = []
    for f in data["features"]:
        g = f["geometry"]
        parts = g["coordinates"] if g["type"] == "MultiPolygon" else [g["coordinates"]]
        polys.append((f["properties"]["shapeName"], parts))

    lons = [p[0] for _, parts in polys for poly in parts for ring in poly for p in ring]
    lats = [p[1] for _, parts in polys for poly in parts for ring in poly for p in ring]
    lon0, lon1, lat0, lat1 = min(lons), max(lons), min(lats), max(lats)
    scale = (W - 2 * PAD) / (lon1 - lon0)  # near the equator, degrees of lat and lon are close enough
    H = round((lat1 - lat0) * scale + 2 * PAD)
    proj = lambda lon, lat: (PAD + (lon - lon0) * scale, PAD + (lat1 - lat) * scale)

    out, total = {}, 0
    for name, parts in polys:
        name = RENAME.get(name, name)
        d, best = [], (0.0, 0.0, 0.0)
        for poly in parts:
            for ri, ring in enumerate(poly):
                pts = [proj(lon, lat) for lon, lat in ring]
                simp = rdp_ring(pts, TOL)
                if len(simp) < 4:
                    continue
                total += len(simp)
                d.append("M" + "L".join(f"{x:.1f},{y:.1f}" for x, y in simp[:-1]) + "Z")
                if ri == 0:
                    a, cx, cy = ring_area_centroid(simp[:-1])
                    if abs(a) > abs(best[0]):
                        best = (a, cx, cy)
        out[name] = {"d": "".join(d), "cx": round(best[1], 1), "cy": round(best[2], 1)}

    js = ("/* Kenya counties (47). Boundaries: geoBoundaries gbOpen KEN ADM1, RCMRD GeoPortal, public domain.\n"
          "   Generated by tools/build_kenya_map.py. */\n"
          f"window.KENYA_MAP = {json.dumps({'w': W, 'h': H, 'source': 'geoBoundaries (RCMRD), public domain', 'counties': out}, separators=(',', ':'))};\n")
    open("assets/js/kenya-map.js", "w", encoding="utf-8").write(js)
    print(f"{len(out)} counties, {total} points, {len(js) / 1024:.1f} KB, {W}x{H}")


if __name__ == "__main__":
    main(sys.argv[1])
